[project]
name = "jewelry-api"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "sqlalchemy>=2.0",
  "psycopg[binary]>=3.2",
  "pydantic>=2",
  "python-multipart",
  "passlib[bcrypt]",
  "pyjwt",
]

[tool.uvicorn]
reload = true
